services:
  postgres-db:
    container_name: banco-db-postgres
    image: postgres:12-alpine
    restart: always
    env_file: .env
    environment:
      POSTGRES_USER: ${DATABASE_USER_POSTGRES}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD_POSTGRES}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    networks:
      - banco-network


  mongo-db:
    container_name: banco-db-mongo
    image: mongo:4.4
    restart: always
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DATABASE_USER_MONGO}
      MONGO_INITDB_ROOT_PASSWORD: ${DATABASE_PASSWORD_MONGO}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
    volumes:
      - ./mongo-prod/initMongo.js:/docker-entrypoint-initdb.d/initMongo.js
    networks:
      - banco-network

  redis:
    container_name: banco-redis
    image: redis:7.4.1
    restart: always
    env_file:
      - .env
    volumes:
      - redis-data:/data
    networks:
      - banco-network

  vives-bank:
    container_name: vives-bank
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    depends_on:
      - postgres-db
      - mongo-db
      - redis
    volumes:
      - bank-data:/app/
      - documentation_doc:/app/doc
      - documentation_jacoco:/app/jacoco
      - documentation_tests:/app/tests
    ports:
      - ${API_PORT}:3000
    networks:
      - banco-network

  apache_doc:
    image: ubuntu/apache2:latest
    container_name: apache_doc
    volumes:
      - documentation_doc:/var/www/html/
      - ./despliegueServers/apacheDoc/000-default.conf:/etc/apache2/sites-available/000-default.conf
    restart: always
    depends_on:
      - vives-bank
    networks:
      - banco-network

  nginx_coverage:
      image: ubuntu/nginx:latest
      container_name: nginx_coverage
      volumes:
        - documentation_jacoco:/var/www/html/
        - ./despliegueServers/nginxCoverage/default:/etc/nginx/sites-available/default
      restart: always
      depends_on:
        - vives-bank
      networks:
        - banco-network

  nginx_test:
      image: ubuntu/nginx:latest
      container_name: nginx_test
      volumes:
        - documentation_tests:/var/www/html/
        - ./despliegueServers/nginxTest/default:/etc/nginx/sites-available/default
      restart: always
      depends_on:
        - vives-bank
      networks:
        - banco-network

  reverse_proxy:
      image: ubuntu/nginx:latest
      container_name: reverse_proxy
      volumes:
        - ./despliegueServers/proxy/nginx.conf:/etc/nginx/nginx.conf
        - ./despliegueServers/proxy/sslcerts:/etc/nginx/certs
      ports:
        - "80:80"
        - "443:443"
      restart: always
      depends_on:
        - nginx_presentacion
        - apache_doc
        - nginx_coverage
        - nginx_test
      networks:
        - banco-network

  nginx_presentacion:
    image: ubuntu/nginx:latest
    container_name: nginx_presentacion
    volumes:
      - ./despliegueServers/presentacion/index.html:/var/www/html/presentacion/index.html
      - ./despliegueServers/presentacion/default:/etc/nginx/sites-available/default
    restart: always
    depends_on:
      - vives-bank
    networks:
      - banco-network




volumes:
  redis-data:
  bank-data:
  documentation_doc:
  documentation_jacoco:
  documentation_tests:

networks:
  banco-network:
    driver: bridge